name = "MultivariateInterpolation"
uuid = "ecbe6ef4-d24e-415b-8de2-e861e2a17b74"
authors = ["Viktor Korotynskiy <korotynskiy.viktor@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"
