name = "AlgebraicInterpolation"
uuid = "ecbe6ef4-d24e-415b-8de2-e861e2a17b74"
authors = ["Viktor Korotynskiy <korotynskiy.viktor@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DecomposingGroupRepresentations = "3934549d-b4b9-4a85-8fa6-9c281fbf1a3e"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
AbstractAlgebra = "0.44.11"
DecomposingGroupRepresentations = "0.1.0"
HomotopyContinuation = "2.13.0"
julia = "1.10"
